In [55]:
import pandas as pd
import plotly.graph_objects as go

In [56]:
def scatter(x, y, *dfs, labels=None, symbols=None, sizes=None):
    """
    Parameters
    ----------
    x, y    : column names for axes
    *dfs    : one or more DataFrames
    labels  : list of legend labels (one per df)
    symbols : list of marker symbols (e.g. "circle", "square", "diamond")
    sizes   : list of marker sizes (px)
    """
    n = len(dfs)
    labels  = labels  or [None] * n
    symbols = symbols or [None] * n
    sizes   = sizes   or [10]   * n

    fig = go.Figure()
    for df, label, symbol, size in zip(dfs, labels, symbols, sizes):
        marker = dict(size=size)
        if symbol:
            marker["symbol"] = symbol
        fig.add_trace(
            go.Scatter(
                x=df[x],
                y=df[y],
                mode="markers",
                name=label,
                text=df["airfoil_name"],
                marker=marker,
                hovertemplate=f"<b>%{{text}}</b><br>{x}=%{{x}}<br>{y}=%{{y}}<extra></extra>",
            )
        )
    fig.update_layout(
        title=f"{y.upper()} vs. {x.upper()}",
        template="plotly_white",
        height=600,
        width=600,
        xaxis_title=x.upper(),
        yaxis_title=y.upper(),
        showlegend=any(l is not None for l in labels),
    )
    fig.show()

In [57]:
df_skin_al_001 = pd.read_csv("results_skin_al_001.csv")
df_skin_al_001 = df_skin_al_001[df_skin_al_001["status"] == "ok"]
print(len(df_skin_al_001))
display(df_skin_al_001.head(5))

90

,airfoil_name,status,error,mu,ea,gj,ei22,ei33
0,apex16,ok,NaN,54.175418,1.383617e+09,3.163747e+06,2.554931e+06,1.083033e+08
1,a18sm,ok,NaN,54.104846,1.381814e+09,9.395590e+05,8.813594e+05,1.089421e+08
2,c141a,ok,NaN,55.100072,1.407232e+09,3.871919e+06,2.969382e+06,1.141240e+08
3,clarkyh,ok,NaN,54.282632,1.386355e+09,2.862847e+06,2.299770e+06,1.091797e+08
4,dae11,ok,NaN,52.701561,1.345975e+09,3.023939e+06,2.887257e+06,9.908722e+07

In [58]:
df_skin_gfrp_001 = pd.read_csv("results_skin_gfrp_001.csv")
df_skin_gfrp_001 = df_skin_gfrp_001[df_skin_gfrp_001["status"] == "ok"]
print(len(df_skin_gfrp_001))
display(df_skin_gfrp_001.head(5))

90

,airfoil_name,status,error,mu,ea,gj,ga22,ga33,ei22,ei33,tc2,tc3,sc2,sc3
0,apex16,ok,NaN,38.838708,7.524147e+08,490355.00339,1.722651e+06,6.644558e+07,1.389254e+06,5.889552e+07,0.232253,0.020259,0.120588,0.029810
1,a18sm,ok,NaN,38.788115,7.514346e+08,145623.97304,7.839131e+05,6.700671e+07,4.791636e+05,5.924289e+07,0.234732,0.026234,0.046549,0.044884
2,clarkyh,ok,NaN,38.915571,7.539038e+08,443717.82773,1.643527e+06,6.671730e+07,1.250496e+06,5.937207e+07,0.232178,0.045370,0.038144,0.063688
3,c141a,ok,NaN,39.501598,7.652568e+08,600115.81442,1.888533e+06,6.767600e+07,1.614633e+06,6.206081e+07,0.236364,0.007858,0.114190,0.011953
4,dae11,ok,NaN,37.782090,7.319451e+08,468685.91819,2.433339e+06,6.420275e+07,1.569979e+06,5.388378e+07,0.209614,0.045294,0.056900,0.077339

In [59]:
df_skin_cfrp_001 = pd.read_csv("results_skin_cfrp_001.csv")
df_skin_cfrp_001 = df_skin_cfrp_001[df_skin_cfrp_001["status"] == "ok"]
print(len(df_skin_cfrp_001))
display(df_skin_cfrp_001.head(5))

90

,airfoil_name,status,error,mu,ea,gj,ga22,ga33,ei22,ei33,tc2,tc3,sc2,sc3
0,apex16,ok,NaN,30.751370,2.728258e+09,8.336154e+05,2.928558e+06,1.129591e+08,5.037404e+06,2.135553e+08,0.232253,0.020259,0.120588,0.029810
1,a18sm,ok,NaN,30.711312,2.724704e+09,2.475643e+05,1.332709e+06,1.139130e+08,1.737414e+06,2.148149e+08,0.234732,0.026234,0.046547,0.044884
2,clarkyh,ok,NaN,30.812228,2.733658e+09,7.543310e+05,2.794050e+06,1.134210e+08,4.534268e+06,2.152833e+08,0.232178,0.045370,0.038143,0.063688
3,c141a,ok,NaN,31.276228,2.774824e+09,1.020211e+06,3.210560e+06,1.150508e+08,5.854629e+06,2.250327e+08,0.236364,0.007858,0.114189,0.011953
4,dae11,ok,NaN,29.914771,2.654035e+09,7.967774e+05,4.136756e+06,1.091462e+08,5.692714e+06,1.953827e+08,0.209614,0.045294,0.056899,0.077339

In [60]:
plot_labels = ["Aluminum Alloy", "Glass Epoxy UD", "Carbon Epoxy UD"]
plot_markers = ["circle", "square", "triangle-up"]
# plot_marker_colors = ["blue", "orange", "green"]
plot_marker_sizes = [5, 5, 5]

In [61]:
scatter(
    "mu", "gj",
    df_skin_al_001,
    df_skin_gfrp_001,
    df_skin_cfrp_001,
    labels=plot_labels,
    symbols=plot_markers,
    sizes=plot_marker_sizes
)

In [62]:
scatter(
    "ei22", "ei33",
    df_skin_al_001,
    df_skin_gfrp_001,
    df_skin_cfrp_001,
    labels=plot_labels,
    symbols=plot_markers,
    sizes=plot_marker_sizes
)